# Workflow deploying the app to GHCR

name: Docker Deploy

on:
  push:
    branches: [ master ]
    paths-ignore: [ 'README.md', 'node_modules/**', '**.pptx' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: all
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Build Docker image
      run: |
        docker buildx build . --file=Dockerfile --platform=linux/arm/v7 --tag=ghcr.io/marcauberer/pupil-pick:latest --load
        echo "Build completed"
        docker image ls
    - name: Push Docker image
      run: |
        echo ${CR_PAT} | docker login ghcr.io -u ${GITHUB_REPOSITORY_OWNER} --password-stdin
        echo "Login successful"
        docker push ghcr.io/marcauberer/pupil-pick:latest
        echo "Push successful"
      env:
        CR_PAT: ${{ secrets.CR_PAT }}
