# Workflow deploying the app to GHCR

name: Docker Deploy

on:
  push:
    branches: [ master ]
    paths-ignore: [ 'README.md', 'node_modules/**', '**.pptx' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Node 12.x
      uses: actions/setup-node@v1
    - name: Load dependencies from cache
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - name: Install & Build
      run: |
        yarn install
        yarn run build
    - name: Build Docker image
      run: |
        docker buildx build . --file Dockerfile --platform "linux/arm/v7" --tag ghcr.io/marcauberer/pupil-pick:latest --output type=image,push=false
        echo "Build completed"
        docker image ls
    - name: Push Docker image
      run: |
        echo ${CR_PAT} | docker login ghcr.io -u ${GITHUB_REPOSITORY_OWNER} --password-stdin
        echo "Login successful"
        docker push ghcr.io/marcauberer/pupil-pick:latest
        echo "Push successful"
      env:
        CR_PAT: ${{ secrets.CR_PAT }}