# Workflow deploying the app to GH Packages

name: Docker Deploy ARMv7

on:
  push:
    branches: [ master ]
    paths-ignore: [ 'README.md', 'node_modules/**', '**.pptx' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: all
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Build Docker image
      run: |
        docker buildx build . --file=Dockerfile-ARMv7 --platform=linux/arm/v7 --tag=docker.pkg.github.com/marcauberer/pupil-pick/pupil-pick-armv7:latest --load
        echo "Build completed"
    - name: Push Docker image
      run: |
        echo ${CR_PAT} | docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY_OWNER} --password-stdin
        echo "Login successful"
        docker push docker.pkg.github.com/marcauberer/pupil-pick/pupil-pick-armv7:latest
        echo "Push successful"
      env:
        CR_PAT: ${{ secrets.CR_PAT }}